// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc.settings
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LegTweaksSettings : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static LegTweaksSettings GetRootAsLegTweaksSettings(ByteBuffer _bb) { return GetRootAsLegTweaksSettings(_bb, new LegTweaksSettings()); }
  public static LegTweaksSettings GetRootAsLegTweaksSettings(ByteBuffer _bb, LegTweaksSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LegTweaksSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float? CorrectionStrength { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float?)null; } }

  public static Offset<solarxr_protocol.rpc.settings.LegTweaksSettings> CreateLegTweaksSettings(FlatBufferBuilder builder,
      float? correction_strength = null) {
    builder.StartTable(1);
    LegTweaksSettings.AddCorrectionStrength(builder, correction_strength);
    return LegTweaksSettings.EndLegTweaksSettings(builder);
  }

  public static void StartLegTweaksSettings(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCorrectionStrength(FlatBufferBuilder builder, float? correctionStrength) { builder.AddFloat(0, correctionStrength); }
  public static Offset<solarxr_protocol.rpc.settings.LegTweaksSettings> EndLegTweaksSettings(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.settings.LegTweaksSettings>(o);
  }
}


}
