// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.pub_sub
{

public enum Payload : byte
{
  NONE = 0,
  solarxr_protocol_datatypes_StringTable = 1,
  solarxr_protocol_datatypes_Bytes = 2,
  KeyValues = 3,
};


}
