// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.pub_sub
{

public enum Topic : byte
{
  NONE = 0,
  TopicHandle = 1,
  TopicId = 2,
};


}
