// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

public enum FirmwareUpdateDeviceId : byte
{
  NONE = 0,
  solarxr_protocol_datatypes_DeviceIdTable = 1,
  SerialDevicePort = 2,
};


}
