// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

public enum FirmwareUpdateMethod : byte
{
  NONE = 0,
  OTAFirmwareUpdate = 1,
  SerialFirmwareUpdate = 2,
};


}
