// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct OSCTrackersSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static OSCTrackersSetting GetRootAsOSCTrackersSetting(ByteBuffer _bb) { return GetRootAsOSCTrackersSetting(_bb, new OSCTrackersSetting()); }
  public static OSCTrackersSetting GetRootAsOSCTrackersSetting(ByteBuffer _bb, OSCTrackersSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public OSCTrackersSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Head { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Chest { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Waist { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Knees { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Feet { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Elbows { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Hands { get { int o = __p.__offset(16); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<solarxr_protocol.rpc.OSCTrackersSetting> CreateOSCTrackersSetting(FlatBufferBuilder builder,
      bool head = false,
      bool chest = false,
      bool waist = false,
      bool knees = false,
      bool feet = false,
      bool elbows = false,
      bool hands = false) {
    builder.StartTable(7);
    OSCTrackersSetting.AddHands(builder, hands);
    OSCTrackersSetting.AddElbows(builder, elbows);
    OSCTrackersSetting.AddFeet(builder, feet);
    OSCTrackersSetting.AddKnees(builder, knees);
    OSCTrackersSetting.AddWaist(builder, waist);
    OSCTrackersSetting.AddChest(builder, chest);
    OSCTrackersSetting.AddHead(builder, head);
    return OSCTrackersSetting.EndOSCTrackersSetting(builder);
  }

  public static void StartOSCTrackersSetting(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddHead(FlatBufferBuilder builder, bool head) { builder.AddBool(0, head, false); }
  public static void AddChest(FlatBufferBuilder builder, bool chest) { builder.AddBool(1, chest, false); }
  public static void AddWaist(FlatBufferBuilder builder, bool waist) { builder.AddBool(2, waist, false); }
  public static void AddKnees(FlatBufferBuilder builder, bool knees) { builder.AddBool(3, knees, false); }
  public static void AddFeet(FlatBufferBuilder builder, bool feet) { builder.AddBool(4, feet, false); }
  public static void AddElbows(FlatBufferBuilder builder, bool elbows) { builder.AddBool(5, elbows, false); }
  public static void AddHands(FlatBufferBuilder builder, bool hands) { builder.AddBool(6, hands, false); }
  public static Offset<solarxr_protocol.rpc.OSCTrackersSetting> EndOSCTrackersSetting(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.OSCTrackersSetting>(o);
  }
}


}
