// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RecordBVHRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static RecordBVHRequest GetRootAsRecordBVHRequest(ByteBuffer _bb) { return GetRootAsRecordBVHRequest(_bb, new RecordBVHRequest()); }
  public static RecordBVHRequest GetRootAsRecordBVHRequest(ByteBuffer _bb, RecordBVHRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RecordBVHRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Stop { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<solarxr_protocol.rpc.RecordBVHRequest> CreateRecordBVHRequest(FlatBufferBuilder builder,
      bool stop = false) {
    builder.StartTable(1);
    RecordBVHRequest.AddStop(builder, stop);
    return RecordBVHRequest.EndRecordBVHRequest(builder);
  }

  public static void StartRecordBVHRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddStop(FlatBufferBuilder builder, bool stop) { builder.AddBool(0, stop, false); }
  public static Offset<solarxr_protocol.rpc.RecordBVHRequest> EndRecordBVHRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.RecordBVHRequest>(o);
  }
}


}
