// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResetResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static ResetResponse GetRootAsResetResponse(ByteBuffer _bb) { return GetRootAsResetResponse(_bb, new ResetResponse()); }
  public static ResetResponse GetRootAsResetResponse(ByteBuffer _bb, ResetResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResetResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.rpc.ResetType ResetType { get { int o = __p.__offset(4); return o != 0 ? (solarxr_protocol.rpc.ResetType)__p.bb.Get(o + __p.bb_pos) : solarxr_protocol.rpc.ResetType.Yaw; } }
  public solarxr_protocol.rpc.ResetStatus Status { get { int o = __p.__offset(6); return o != 0 ? (solarxr_protocol.rpc.ResetStatus)__p.bb.Get(o + __p.bb_pos) : solarxr_protocol.rpc.ResetStatus.STARTED; } }

  public static Offset<solarxr_protocol.rpc.ResetResponse> CreateResetResponse(FlatBufferBuilder builder,
      solarxr_protocol.rpc.ResetType reset_type = solarxr_protocol.rpc.ResetType.Yaw,
      solarxr_protocol.rpc.ResetStatus status = solarxr_protocol.rpc.ResetStatus.STARTED) {
    builder.StartTable(2);
    ResetResponse.AddStatus(builder, status);
    ResetResponse.AddResetType(builder, reset_type);
    return ResetResponse.EndResetResponse(builder);
  }

  public static void StartResetResponse(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddResetType(FlatBufferBuilder builder, solarxr_protocol.rpc.ResetType resetType) { builder.AddByte(0, (byte)resetType, 0); }
  public static void AddStatus(FlatBufferBuilder builder, solarxr_protocol.rpc.ResetStatus status) { builder.AddByte(1, (byte)status, 0); }
  public static Offset<solarxr_protocol.rpc.ResetResponse> EndResetResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.ResetResponse>(o);
  }
}


}
