// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResetRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static ResetRequest GetRootAsResetRequest(ByteBuffer _bb) { return GetRootAsResetRequest(_bb, new ResetRequest()); }
  public static ResetRequest GetRootAsResetRequest(ByteBuffer _bb, ResetRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResetRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.rpc.ResetType ResetType { get { int o = __p.__offset(4); return o != 0 ? (solarxr_protocol.rpc.ResetType)__p.bb.Get(o + __p.bb_pos) : solarxr_protocol.rpc.ResetType.Yaw; } }

  public static Offset<solarxr_protocol.rpc.ResetRequest> CreateResetRequest(FlatBufferBuilder builder,
      solarxr_protocol.rpc.ResetType reset_type = solarxr_protocol.rpc.ResetType.Yaw) {
    builder.StartTable(1);
    ResetRequest.AddResetType(builder, reset_type);
    return ResetRequest.EndResetRequest(builder);
  }

  public static void StartResetRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddResetType(FlatBufferBuilder builder, solarxr_protocol.rpc.ResetType resetType) { builder.AddByte(0, (byte)resetType, 0); }
  public static Offset<solarxr_protocol.rpc.ResetRequest> EndResetRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.ResetRequest>(o);
  }
}


}
