// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// Sends the GET WIFISCAN cmd to the current tracker on the serial monitor
public struct SerialTrackerGetWifiScanRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static SerialTrackerGetWifiScanRequest GetRootAsSerialTrackerGetWifiScanRequest(ByteBuffer _bb) { return GetRootAsSerialTrackerGetWifiScanRequest(_bb, new SerialTrackerGetWifiScanRequest()); }
  public static SerialTrackerGetWifiScanRequest GetRootAsSerialTrackerGetWifiScanRequest(ByteBuffer _bb, SerialTrackerGetWifiScanRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SerialTrackerGetWifiScanRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSerialTrackerGetWifiScanRequest(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<solarxr_protocol.rpc.SerialTrackerGetWifiScanRequest> EndSerialTrackerGetWifiScanRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.SerialTrackerGetWifiScanRequest>(o);
  }
}


}
