// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

public enum StatusData : byte
{
  NONE = 0,
  StatusTrackerReset = 1,
  StatusTrackerError = 2,
  StatusSteamVRDisconnected = 3,
  StatusUnassignedHMD = 4,
};


}
