// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StopWifiProvisioningRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static StopWifiProvisioningRequest GetRootAsStopWifiProvisioningRequest(ByteBuffer _bb) { return GetRootAsStopWifiProvisioningRequest(_bb, new StopWifiProvisioningRequest()); }
  public static StopWifiProvisioningRequest GetRootAsStopWifiProvisioningRequest(ByteBuffer _bb, StopWifiProvisioningRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StopWifiProvisioningRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartStopWifiProvisioningRequest(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<solarxr_protocol.rpc.StopWifiProvisioningRequest> EndStopWifiProvisioningRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.StopWifiProvisioningRequest>(o);
  }
}


}
