// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

public enum WifiProvisioningStatus : byte
{
  NONE = 0,
  SERIAL_INIT = 1,
  PROVISIONING = 2,
  CONNECTING = 3,
  CONNECTION_ERROR = 4,
  LOOKING_FOR_SERVER = 5,
  COULD_NOT_FIND_SERVER = 6,
  DONE = 7,
  OBTAINING_MAC_ADDRESS = 8,
};


}
