// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace solarxr_protocol.rpc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct YawCorrectionSettings : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static YawCorrectionSettings GetRootAsYawCorrectionSettings(ByteBuffer _bb) { return GetRootAsYawCorrectionSettings(_bb, new YawCorrectionSettings()); }
  public static YawCorrectionSettings GetRootAsYawCorrectionSettings(ByteBuffer _bb, YawCorrectionSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public YawCorrectionSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Enabled { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float AmountInDegPerSec { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<solarxr_protocol.rpc.YawCorrectionSettings> CreateYawCorrectionSettings(FlatBufferBuilder builder,
      bool enabled = false,
      float amountInDegPerSec = 0.0f) {
    builder.StartTable(2);
    YawCorrectionSettings.AddAmountInDegPerSec(builder, amountInDegPerSec);
    YawCorrectionSettings.AddEnabled(builder, enabled);
    return YawCorrectionSettings.EndYawCorrectionSettings(builder);
  }

  public static void StartYawCorrectionSettings(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEnabled(FlatBufferBuilder builder, bool enabled) { builder.AddBool(0, enabled, false); }
  public static void AddAmountInDegPerSec(FlatBufferBuilder builder, float amountInDegPerSec) { builder.AddFloat(1, amountInDegPerSec, 0.0f); }
  public static Offset<solarxr_protocol.rpc.YawCorrectionSettings> EndYawCorrectionSettings(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<solarxr_protocol.rpc.YawCorrectionSettings>(o);
  }
}


}
